### ISSUE TITLE
I need screenshor or demo url if possible?

### ISSUE THREAD

**Issue by johnfelipe** [SEMICeu/e-legislation-pilot#1]

**Comment by jensscheerlinck** [comment]
Hello John,

Thank you for your interest!
We foresee to provide a demo URL around end of May.

Kind regards,
Jens

**Comment by johnfelipe** [comment]
Any advance

**Comment by jensscheerlinck** [comment]
Hi there!

You can find documentation regarding the data model in the directory: `/ELI_Visualisation/doc/index.html`, this is also hosted on: http://52.50.205.146/legislation-pilot/doc/index.html

Also, an Alpha version of the pilot can be found here: http://52.50.205.146/legislation-pilot/
