### ISSUE TITLE
cited_by and cites are defined as owl:inverseOf, but in their definition they have the same domain and range.

### ISSUE THREAD

**Issue by gezever** [SEMICeu/e-legislation-pilot#2]
ObjectProperty http://data.europa.eu/eli/ontology#cited_by and http://data.europa.eu/eli/ontology#cites are defined as owl:inverseOf

But in their definition they are not inverse, and have the same domain and range.

Thus,
    

    <owl:ObjectProperty rdf:about="http://data.europa.eu/eli/ontology#cited_by">
        <owl:inverseOf rdf:resource="http://data.europa.eu/eli/ontology#cites"/>
        <rdfs:domain>
            <owl:Class>
                <owl:unionOf rdf:parseType="Collection">
                    <rdf:Description rdf:about="http://data.europa.eu/eli/ontology#LegalExpression"/>
                    <rdf:Description rdf:about="http://data.europa.eu/eli/ontology#LegalResource"/>
                </owl:unionOf>
            </owl:Class>
        </rdfs:domain>
        <rdfs:range rdf:resource="http://www.w3.org/2002/07/owl#Thing"/>
        <specificPropertyOf rdf:resource="http://purl.org/dc/terms/relation"/>
        <rdfs:comment xml:lang="en">Inverse of &quot;cites&quot;</rdfs:comment>
        <rdfs:label xml:lang="en">cited by</rdfs:label>
        <owl:versionInfo>created in v1.0</owl:versionInfo>
    </owl:ObjectProperty>
    

    

    <owl:ObjectProperty rdf:about="http://data.europa.eu/eli/ontology#cites">
        <rdfs:domain>
            <owl:Class>
                <owl:unionOf rdf:parseType="Collection">
                    <rdf:Description rdf:about="http://data.europa.eu/eli/ontology#LegalExpression"/>
                    <rdf:Description rdf:about="http://data.europa.eu/eli/ontology#LegalResource"/>
                </owl:unionOf>
            </owl:Class>
        </rdfs:domain>
        <rdfs:range rdf:resource="http://www.w3.org/2002/07/owl#Thing"/>
        <specificPropertyOf rdf:resource="http://purl.org/dc/terms/relation"/>
        <rdfs:comment xml:lang="en">Citation in the text of the legislation. This may be at the legal resource or legal expression level, as required by the implementation context. This includes verbatim citation and citations in referrals.</rdfs:comment>
        <rdfs:label xml:lang="en">cites</rdfs:label>
        <owl:versionInfo>created in v1.0</owl:versionInfo>
    </owl:ObjectProperty>

Should be:

    

    <owl:ObjectProperty rdf:about="http://data.europa.eu/eli/ontology#cited_by">
        <owl:inverseOf rdf:resource="http://data.europa.eu/eli/ontology#cites"/>
        <rdfs:range>
            <owl:Class>
                <owl:unionOf rdf:parseType="Collection">
                    <rdf:Description rdf:about="http://data.europa.eu/eli/ontology#LegalExpression"/>
                    <rdf:Description rdf:about="http://data.europa.eu/eli/ontology#LegalResource"/>
                </owl:unionOf>
            </owl:Class>
        </rdfs:range>
        <rdfs:domain rdf:resource="http://www.w3.org/2002/07/owl#Thing"/>
        <specificPropertyOf rdf:resource="http://purl.org/dc/terms/relation"/>
        <rdfs:comment xml:lang="en">Inverse of &quot;cites&quot;</rdfs:comment>
        <rdfs:label xml:lang="en">cited by</rdfs:label>
        <owl:versionInfo>created in v1.0</owl:versionInfo>
    </owl:ObjectProperty>
    

    

    <owl:ObjectProperty rdf:about="http://data.europa.eu/eli/ontology#cites">
        <rdfs:domain>
            <owl:Class>
                <owl:unionOf rdf:parseType="Collection">
                    <rdf:Description rdf:about="http://data.europa.eu/eli/ontology#LegalExpression"/>
                    <rdf:Description rdf:about="http://data.europa.eu/eli/ontology#LegalResource"/>
                </owl:unionOf>
            </owl:Class>
        </rdfs:domain>
        <rdfs:range rdf:resource="http://www.w3.org/2002/07/owl#Thing"/>
        <specificPropertyOf rdf:resource="http://purl.org/dc/terms/relation"/>
        <rdfs:comment xml:lang="en">Citation in the text of the legislation. This may be at the legal resource or legal expression level, as required by the implementation context. This includes verbatim citation and citations in referrals.</rdfs:comment>
        <rdfs:label xml:lang="en">cites</rdfs:label>
        <owl:versionInfo>created in v1.0</owl:versionInfo>
    </owl:ObjectProperty>

**Comment by bertvannuffelen** [comment]
closed because of archiving
